# Generated by Django 3.2.12 on 2024-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_received_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('req_received_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('request', models.CharField(max_length=200)),
                ('response', models.JSONField()),
            ],
        ),
    ]
