# Generated by Django 3.2.12 on 2024-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststore',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
