# Generated by Django 3.2.12 on 2024-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_requeststore_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststore',
            name='response',
            field=models.JSONField(),
        ),
    ]
