# Generated by Django 3.2.12 on 2024-03-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_requeststore_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('vip', models.CharField(max_length=255)),
                ('car_number_plate', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
                ('booking', models.DateTimeField()),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='UserAnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateField()),
                ('no_of_users', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
        migrations.AlterModelTable(
            name='requeststore',
            table='request_store',
        ),
    ]
